package com.iitm.hosteldine.constant.hostel;

import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public enum HostelConstants {
    STUDENT_COMPLAINT_CONFIG_FORM_KEY("studentComplaintConfigurationDto"),
    WORKFLOW_MASTER_FORM_KEY("workflowMasterDto"),
    WORKFLOW_MASTER_CATEGORY("workflowCategory"),
    HOSTEL_ALLOTMENT_GUI_STATUS("hostelAllotmentStatus"),
    WORKFLOW_MASTER_AUTHORITY_TYPE("workflowAuthorityType"),
    GIRLS_ONE_MESS_LIST("girlsOneMessList"),
    GIRLS_TWO_MESS_LIST("girlsTwoMessList"),
    GOOD("Good"),
    INVALID_HOSTEL_ID("Invalid 'hostelId' parameter"),
    BOYS_ONE_MESS_LIST("boysOneMessList"),
    HOSTEL_LIST("hostelList"),
    HOSTEL_OR_WARDEN_LIST("hostelOrWardenList"),
    ERROR_MESSAGE_KEY("errorMessage"),
    STUDENT_AVAILABLE_INFO("Student ID not found"),
    MONTH_OFFSET("monthOffset"),
    CURRENT_DATE("currentDate"),
    START_DATE("startDate"),
    DATE_SEQUENCE("dateSequence"),
    VACANCY_MAP("vacancyMap"),
    END_DATE("endDate"),
    DATE("date"),
    WARDEN("Warden"),
    OCCUPANCY_STATUS("occupancyStatus"),
    APPOINTMENT_NATURE("appointmentNature"),
    ROOM_LIST("roomList"),
    HOSTEL_ROOM_INFO_DTO("hostelRoomInfoDto"),
    HOSTEL_FLOOR_MASTER_MASTER_DTO("hostelFloorMasterDto"),
    HOSTEL_FLOOR_NAME("hostelFloorName"),
    HOSTEL_MASTER_DTO("hostelMasterDto"),
    ROOM_OCCUPANCY_DETAILS("roomOccupancyDetails"),
    TOTAL_VACANT_SEATS("totalVacantSeats"),
    MESS_REGISTRATION_MAPPING("messRegistrationMapping"),
    A("a"),
    F("f"),
    M("m"),
    MESS("mess"),
    MESSES("messes"),
    SEARCHED_COUPONS("searchedCoupons"),
    COUPON("coupon"),
    CANDIDATE("candidate"),
    DIRECT("direct"),
    STUDENT("student"),
    STUDENT_APP("StudentApp"),
    CANDIDATE_CAPS("Candidate"),
    STUDENT_CAPS("Student"),
    FEMALE("Female"),
    MALE("Male"),
    COUPON_STATUSES("couponStatuses"),
    OFFICIAL_GUEST_STATUS_PD("pd"),
    OFFICIAL_GUEST_STATUS_NOT_FIT("notfit"),
    COUPON_CATEGORIES("categories"),
    PAYMENT_STATUS("paymentStatuses"),
    HOSTEL_ID("hostelId"),
    FLOOR_ID("floorId"),
    ROOM_ID("roomId"),
    STAY_FROM("stayFrom"),
    STAY_TO("stayTo"),
    STAY_FROM_DATE("stay_from_date"),
    STAY_TO_DATE("stay_to_date"),
    FILTER_VALUE("filterValue"),
    EMAIL("email"),
    STUDENT_ID("student_id"),
    ROOM_NO("Room No."),
    ERROR_MESSAGE_VALUE("You do not have access to view this information."),
    ACCOMMODATION_FOR_THE("Accommodation for the"),
    CANDIDATE_WITH_EMAIL_ID("Candidate with Email Id"),
    STUDENT_WITH_EMAIL_ID("Student with student Id"),
    NOT_AVAILABLE_OR_APPROVED("is Not Available / Approved, to allocate for the selected date."),
    ALLOTTED_FOR_SAME_DATE("is already allotted for the same date."),
    REQUEST_NOT_APPROVED("Request is not Approved yet, for the selected date."),
    IN_THIS_HOSTEL("In this Hostel"),
    CANT_BE_ALLOWED("can't be allowed"),
    STUDENT_DOESNT_EXIST("Student Doesn't Exist"),
    ROOM_ALREADY_OCCUPIED("Room Already Occupied"),
    YOU_HAVE_BEEN_ALLOTTED("You have been allotted to the Hostel"),
    STD_CANDIDATE_ALREADY_EXIST("This Student / Candidate is already allotted for the same date"),
    OTHER_CANDIDATE_AVAILABLE_INFO("Other Candidate information not available"), 
    AMOUNT("Amount"),
    AMOUNT_VALUE_LENGTH_VALIDATION("Amount value can have up to 10 digits before the decimal and up to 2 digits after :"),
    AMOUNT_INCORRECT_FORMAT("Amount format is incorrect. Value must be a number :"), 
    AMOUNT_SHOULD_BE_GREATER_THAN_ZERO("Amount should be greater than zero :");

    private final String constants;

    HostelConstants(String constants) {
        this.constants = constants;
    }
}
