spring.application.name=Hosteldine
server.servlet.context-path=/iitmhostel
server.port=8080
application.name=iitmhostel
build.version=1.0.129

logging.level.com.iitm.hosteldine=INFO
spring.messages.basename=messages,url-text,label-text,validation-text
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.jvm.args=--add-opens java.base/java.lang=ALL-UNNAMED
#logging.level.com.sun.xml.ws.transport.http.client.HttpTransportPipe=DEBUG

#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/iitm_dev
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
#Database config ends here

#JPA Config starts here
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
#JPA config ends here

#LDAP Config starts here
ldap.uri=ldap://65.109.35.145:389/
ldap.bindDN=cn=admin,dc=triesten,dc=local,dc=com
ldap.bind.password=sPlz*br22
ldap.base=dc=triesten,dc=local,dc=com
ldap.context.factory=com.sun.jndi.ldap.LdapCtxFactory
#LDAP Config ends here
#Session Config starts here
server.servlet.session.timeout=30h
#Session Config ends here

#Custom Config Starts here
#Expiry set in millis to 2 mins for test purpose
url.expiry.duration=120000
#Custom Config Ends here

#backend-validation-button
backend.validation.button=Y

#Payment gateway Instance
merchant.id=171377

#Duration of error page redirection
conf.errorPageRedirect=500

enable.role.privilege=true

#cron for push,collect and clearing the logs
#Syntax: <second> <MinuteOfHour> <HourOfDay> <DayOfMonth> <Month> <DayOfWeek>
daily.at.midnight= 0 5 0 * * *
daily.at.end.of.day=0 50 23 * * *
clear.iot.logs=0 0 1 1 * *
delete.iot.logs=1


#Workflow API
#IP Config,token and URL for Sending Data Transfer API Call
#api_data_transfer_ip_list=10.24.2.17,10.24.9.21,10.21.203.183,10.24.0.253,10.24.9.238,10.44.67.163,10.44.67.176
api_data_transfer_ip_list=10.24.2.17,10.21.200.60,10.21.200.73,10.24.2.15,10.24.2.10,10.44.65.193,10.44.66.217,10.44.65.193
api_data_transfer_token=0a96b4cc5bc0e4f72c3a3199c08427d5
student_data_transfer_api_url=http://ikollege.iitm.ac.in/iitmhostel/workFlowApi/student
warden_data_transfer_api_url=http://ikollege.iitm.ac.in/iitmhostel/workFlowApi/warden
