server.port=8082

#Database config starts here
spring.datasource.url=jdbc:postgresql://65.109.35.159:10691/iitchennai
spring.datasource.username=postgres
spring.datasource.password=W$lkl3TlPo
#Database config ends here

#JPA Config starts here
spring.jpa.show-sql=true
#JPA config ends here

#Session Config starts here
server.servlet.session.timeout=30h
#Session Config ends here
url.expiry.duration=1200000
