server.port=8080

#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/CCW-IITM
#spring.datasource.url=jdbc:postgresql://5.161.234.2:10691/archivewithoutdata
#spring.datasource.url=jdbc:postgresql://65.109.35.159:10691/archivewithoutdata
spring.datasource.username=postgres
spring.datasource.password=root
#spring.datasource.password=W$lkl3TlPo
#staging password=G$lkl3TlPo
#iskool password=W$lkl3TlPo
#Database config ends here

#JPA Config starts here
spring.jpa.show-sql=true
#JPA config ends here

#Session Config starts here
server.servlet.session.timeout=30h
#Session Config ends here

#backend-validation-button
backend.validation.button=Y
