spring.application.name=Hosteldine

logging.level.com.iitm.hosteldine=DEBUG
spring.messages.basename=messages,url-text,buttons-text,label-text,validation-text

server.port=8901

#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/ccw_aug_29
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
#Database config ends here

#JPA Config starts here
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
#JPA config ends here

#LDAP Config starts here
ldap.uri=ldap://65.109.35.145:389/
ldap.bindDN=cn=admin,dc=triesten,dc=local,dc=com
ldap.bind.password=sPlz*br22
ldap.base=dc=triesten,dc=local,dc=com
ldap.context.factory=com.sun.jndi.ldap.LdapCtxFactory
#LDAP Config ends here
#Session Config starts here
server.servlet.session.timeout=30h
#Session Config ends here
server.servlet.context-path=/hosteldine

