server.port=8080
server.servlet.session.tracking-modes=cookie

# Local PostgreSQL Database Config
spring.datasource.url=jdbc:postgresql://localhost:5432/iitm_dev
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Local JPA Config
spring.jpa.show-sql=true
