#port
server.port=8082
#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/ccw_nov_13
spring.datasource.username=postgres
spring.datasource.password=$@nju#29
#Database config ends here

#JPA Config starts here
spring.jpa.show-sql=true
#JPA config ends here

#Session Config starts here
server.servlet.session.timeout=30h
#Session Config ends here
url.expiry.duration=1200000
spring.messages.basename=messages,url-text,label-text,validation-text

spring.web.resources.static-locations=classpath:/static/
spring.messages.encoding=UTF-8
