server.port=8900

#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/ccwnov
#spring.datasource.url=jdbc:postgresql://65.109.35.159:10691/archivewithoutdata
#spring.datasource.password=W$lkl3TlPo
spring.datasource.username=postgres
spring.datasource.password=admin


#Database config ends here
server.servlet.session.timeout=30h
server.servlet.context-path=/hosteldine
url.expiry.duration=1200000000