server.port=8901

#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/ccw_29
spring.datasource.username=postgres
spring.datasource.password=password
#Database config ends here

