server.port=8080

#Database config starts here
spring.datasource.url=jdbc:postgresql://localhost:5432/ccw
spring.datasource.username=postgres
spring.datasource.password=admin
#Database config ends here

#JPA Config starts here
spring.jpa.show-sql=true
#JPA config ends here

#Session Config starts here
server.servlet.session.timeout=30h
#Session Config ends here

#Session Config ends here
server.servlet.context-path=/hosteldine

