package com.iitm.hosteldine.service;

import com.iitm.hosteldine.config.SecurityCtxUtil;
import com.iitm.hosteldine.constant.AutoGenerateString;
import com.iitm.hosteldine.constant.Constants;
import com.iitm.hosteldine.constant.ModelConstants;
import com.iitm.hosteldine.dto.UserManagementOnlineDto;
import com.iitm.hosteldine.entity.UserManagementOnlineEntity;
import com.iitm.hosteldine.entity.mailQueue.MailTemplateEntity;
import com.iitm.hosteldine.repository.UserManagementOnlineRepository;
import com.iitm.hosteldine.repository.UserManagementRepository;
import com.iitm.hosteldine.repository.mailQueue.MailTemplateRepository;
import com.iitm.hosteldine.service.mailQueue.MailQueueService;
import com.iitm.hosteldine.util.MD5Encryption;
import com.iitm.hosteldine.util.response.CommonResponseUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.Optional;

@Service
@RequiredArgsConstructor
public class OtherUserService {
    private final UserManagementOnlineRepository userManagementOnlineRepository;
    private final MailQueueService mailQueueService;
    private final UserManagementRepository userManagementRepository;
    private final CommonResponseUtil commonResponseUtil;
    private final MailTemplateRepository mailTemplateRepository;

    @Transactional
    public String saveOtherLogin(UserManagementOnlineDto userManagementForm) {
            UserManagementOnlineEntity userManagementEntity = new UserManagementOnlineEntity();
            userManagementEntity.setFirstName(userManagementForm.getApplicantName());
            userManagementEntity.setPassword(MD5Encryption.md5Encrypt(userManagementForm.getApplicantPassword()));
            userManagementEntity.setUserEmailId(userManagementForm.getApplicantEmail().trim().toLowerCase());
            userManagementEntity.setEmail(userManagementForm.getApplicantEmail().trim().toLowerCase());
            userManagementEntity.setLastLoginTime(LocalDateTime.now());
            userManagementEntity.setLastName("");
            userManagementEntity.setActiveStatus(ModelConstants.NOT_BLOCKED);
            userManagementEntity.setNoOfFailedAttempts(0L);
        //save user management
        UserManagementOnlineEntity userManagementEntity1 = userManagementOnlineRepository.saveAndFlush(userManagementEntity);
        //saved user id is updated in created by and modified by
        userManagementEntity1.setCreatedBy(String.valueOf(userManagementEntity.getUserId()));
        userManagementEntity1.setModifiedBy(String.valueOf(userManagementEntity.getUserId()));
            userManagementOnlineRepository.save(userManagementEntity1);
        return Constants.SAVED;
    }

    public boolean checkEmailIdExist(String applicantEmail) {
        return userManagementOnlineRepository.existsByEmailIgnoreCaseAndActiveFlag(applicantEmail.trim().toLowerCase(), ModelConstants.STATUS_ACTIVE);
    }

    @Transactional
    public String forgotPassword(String emailId) {
        Optional<UserManagementOnlineEntity> optionalUserManagementOnlineEntity = userManagementOnlineRepository.findByUserEmailIdAndActiveFlag(emailId, ModelConstants.STATUS_ACTIVE);
        return optionalUserManagementOnlineEntity.map(userManagementOnlineEntity -> {
            AutoGenerateString autoGeneratedString = new AutoGenerateString();
            String password = autoGeneratedString.nextString(ModelConstants.PASSWORD_LENGTH);
            userManagementOnlineEntity.setPassword(MD5Encryption.md5Encrypt(password));
            userManagementOnlineEntity.setPasswordModifiedTime(LocalDateTime.now());
            userManagementOnlineEntity.setModifiedAt(LocalDateTime.now());
            userManagementOnlineEntity.setNoOfFailedAttempts(0L);
            userManagementOnlineEntity.setActiveStatus(ModelConstants.NOT_BLOCKED);
            userManagementOnlineRepository.save(userManagementOnlineEntity);
            String mailTemplate = mailTemplate(password, emailId);
            try {
                mailQueueService.saveMailQueue(
                        commonResponseUtil.getMessage("message.validate.other.candidate.password.reset"),
                        commonResponseUtil.getMessage("message.mail.greetings.for"), mailTemplate, emailId,
                        commonResponseUtil.getMessage("message.validate.password.reset"), SecurityCtxUtil.userName(), null,null, null,
                        ModelConstants.REGARDS, ModelConstants.CCW_OFFICE);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
            return ModelConstants.SUCCESS;
        }).orElse(ModelConstants.PASSWORD_MISMATCH);

    }

    private String mailTemplate(String password, String emailId) {
        Optional<MailTemplateEntity> candidateResetPasswordMailTemplate = mailTemplateRepository
                .findByMailType(MailTemplateEntity.OTHER_CANDIDATE_PASSWORD_RESET_CONTENT);
        if (candidateResetPasswordMailTemplate.isPresent()) {
            String mailTemplate = candidateResetPasswordMailTemplate.get().getMailTemplate();
            mailTemplate = mailTemplate.replaceAll("#%userName%#", emailId);
            mailTemplate = mailTemplate.replaceAll("#%password%#", password);
            return mailTemplate;
        }
        return ModelConstants.EMPTY_STRING;
    }
}
