package com.iitm.hosteldine.util;

public enum CommonEnum {
	STUDENT_PROFILE,
	STUDENT_IMAGE,
	PROFILE,
	SHOW,
	SEAT,BF,LC,DR,ET,
	CANDIDATE_PROFILE,
	CANDIDATE_IMAGE,
	GUEST_ACCOMMODATION,
	HOSTEL_ACCOMMODATION,
	WARDEN_IMAGE,
	ROLL_NO_CHANGE,
    STUDENT_COMPLAINT_CONFIG,
    BIO_DATA_PARENT_PROOF,
    HDC_COMPLAINT_FILE_PATH,
	MESS_INSPECTION_FILE_PATH,
}
