package com.iitm.hosteldine.constant.dashboard.student;

import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public enum StudentConstants {
    OCCUPANCY("message.label.multi"),
    Y("message.label.y"),
    S("message.label.s"),
    D("message.label.d"),
    SCHOLAR_STAY_EXTENSION_SAVE("message.scholars.stay.extension.save"),
    SCHOLAR_STAY_EXTENSION_CANCEL("message.scholars.stay.extension.cancel"),
    HOSTEL_ACCOMMODATION_FILE_SAVE("message.hostel.accommodation.file.save"),
    SCHOLAR_STAY_EXTENSION_RESEND_EMAIL("message.scholars.stay.extension.resend.email"),
    PHD_THESIS_STATUS("message.label.phd.thesis.status"),
    MS_THESIS_STATUS("message.label.ms.thesis.status"),
    PURPOSE("message.label.scholars.purpose"),
    CATEGORY_SCHOLAR("message.label.scholar"),
    CATEGORY_INSIDE_CAMPUS("message.label.inside.campus"),
    CATEGORY_OUTSIDE_CAMPUS("message.label.outside.campus"),
    CATEGORY_INTERN_INSIDE_CAMPUS("message.label.intern.inside.campus"),
    CATEGORY_INTERN_OUTSIDE_CAMPUS("message.label.intern.outside.campus"),
    AUTHORITY_TYPE_DEAN("message.label.dean"),
    AUTHORITY_TYPE_DEAN_STUDENT("message.label.dean.student"),
    AUTHORITY_TYPE_DEAN_DOST("message.label.dean.dost"),
    CATEGORY_DOST("message.label.dost"),
    VALIDATOR("message.label.validator"),
    HOD("message.label.hod"),
    MAIL_TEMPLATE_SCHOLAR_LEVEL("ScholarCommonMailTemplate"),
    COMMON_MAIL_TEMPLATE_HOSTEL_VACATING_FORM("message.label.student.room.vacating.form"),
    MAIL_TEMPLATE_HOSTEL_VACATING_FORM("message.label.student.hostel.vacating.form"),
    BUTTON_TEMPLATE_HOSTEL_VACATING_FORM("message.label.student.hostel.vacating.form.buttons"),
    MAIL_TEMPLATE_HOSTEL_VACATING_NEG_BAL_NOTE("message.label.student.hostel.vacating.neg.bal.note"),
    MAIL_TEMPLATE_NEG_BAL_NOTE("message.label.neg.bal.note"),
    STUDENT_MAIL_TEMPLATE_BODY("ScholarStudentBodyTemplate"),
    OTHERS_MAIL_TEMPLATE_BODY("ScholarOthersBodyTemplate"),
    STUDENT_ACCOMM_APPROVE_REJECT_BUTTON("StudentAccommodationApproveRejectButton"),
    MS_PHD_SCHOLAR_STAY_EXTENSION("message.label.ms.phd.period.stay.extension"),
    HOSTEL_ACCOMM_SCHOLAR_STAY_EXTENSION("message.label.accomm.scholar.stay.extension"),
    DEFAULT_MAIL("message.label.student.scholar.default.mail"),
    SCHOLAR_STAY_EXTENSION_STUDENT_APPOINTMENT("message.label.scholar.stay.extension.student.appointment"),
    MAIL_BODY_STUDENT_NAME("message.label.mail.template.student.name"),
    MAIL_BODY_EMAIL_HEADING("message.label.mail.template.email.heading"),
    MAIL_BODY_STUDENT_ID("message.label.mail.template.student.id"),
    MAIL_BODY_EMAIL_ID("message.label.mail.template.email.id"),
    MAIL_BODY_ADDRESS("message.label.mail.template.address"),
    MAIL_BODY_CONTACT_NUMBER("message.label.mail.template.contact.number"),
    MAIL_BODY_FROM_DATE("message.label.mail.template.from.date"),
    MAIL_BODY_TO_DATE("message.label.mail.template.to.date"),
    MAIL_BODY_CATEGORY("message.label.mail.template.category"),
    MAIL_BODY_PURPOSE("message.label.mail.template.purpose"),
    MAIL_BODY_APPROVAL_URL("message.label.mail.template.approval.url"),
    MAIL_BODY_APPROVAL_BUTTON_TEMPLATE("message.label.mail.template.approval.button.template"),
    MAIL_BODY_NEG_BAL_NOTE("message.label.mail.template.neg.bal.note"),
    MAIL_BODY_REJECT_URL("message.label.mail.template.reject.url"),
    MAIL_BODY_VIEW_URL("message.label.mail.template.view.url"),
    MAIL_BODY_LOGIN_URL("message.label.mail.template.login.url"),
    MAIL_BODY_DATE("message.label.mail.template.date"),
    MAIL_BODY_APPROVE_REJECT_DESC("message.label.mail.template.approve.reject.desc"),
    MAIL_BODY_HEADER_OTHERS("message.label.mail.template.header.other"),
    MAIL_BODY_VACATION_DATE("message.label.mail.template.vacation.date"),
    MAIL_BODY_VACATING_EXCHANGE_PERIOD("message.label.mail.template.vacating.exchange.period"),
    MAIL_BODY_REASON_FOR_VACATING("message.label.mail.template.vacating.reason"),
    MAIL_BODY_HOSTEL_NAME("message.label.mail.template.hostel.name"),
    MAIL_BODY_ROOM_NO("message.label.mail.template.room.number"),
    MAIL_BODY_NEGATIVE_BAL_NOTE("message.label.mail.template.negative.bal.note"),
    MAIL_BODY_BUTTON_TEMPLATE("message.label.mail.template.button.tamplet"),
    HOSTEL_ROOM_VACATING_FORM_SAVE("message.hostel.room.vacating.form.save"),
    HOSTEL_ROOM_VACATING_FORM("message.label.hostel.room.vacating.form"),
    FORM_KEY("message.label.scholars.stay.extension.dto"),
    MS_PHD_STAY_EXTENSION_FLAG("message.label.ms.phd.stay.extension.flag"),
    REASON_FOR_VACATION("message.label.reason.for.vacation"),
    DONATION_TYPE("message.label.donation.type"),
    HOSTEL_ROOM_VACATING_ALLOWED_STUDENT_DTO("message.hostel.vacating.allowed.student.dto"),
    STUDENT_HOSTEL_VACATING_REQ_DTO("message.student.hostel.vacating.req.dto"),
    CREATED_AT("createdAt"),
    STATUS("status"),
    IS_DATE_AND_STATUS_EMPTY("message.label.is.date.and.status.empty"),
    STUDENT_DETAILS_DTO("message.label.student.details.dto"),
    HOSTEL_LIST_DTO("message.label.hostel.list.dto"),
    REASON_FOR_VACATING_LIST("message.label.reason.for.vacating.list"),
    DONATION_TYPE_LIST("message.label.donation.type.list"),
    STD_HOSTEL_ROOM_VACATING_DTO("message.label.std.hostel.room.vacating.req.dto"),
    SUCCESS_NOTE("message.label.success.note"),
    NEG_BAL("message.label.neg.bal"),
    FORM_SUBMITTING_DUE_NOTE("message.label.form.submitting.due.note"),
    FORM_SUBMITTING_APPROVED_NOTE("message.label.form.submitting.approved.note"),
    FORM_SUBMITTING_PENDING_NOTE("message.label.form.submitting.pending.note"),
    FORM_SUBMITTING_CANCELLED_NOTE("message.label.form.submitting.cancelled.note"),
    FORM_SUBMITTING_REJECTED_NOTE("message.label.form.submitting.rejected.note"),
    FORM_SUBMITTED_EMAIL_HEADING("message.label.form.submitted.email.heading"),
    FORM_SUBMITTED_WITH_DUES_EMAIL_HEADING("message.label.form.submitted.with.dues.email.heading"),
    FORM_SUBMITTED_APPROVED_EMAIL_HEADING("message.label.form.submitted.approved.email.heading"),
    VACATING_FORM_APPROVAL_MAIL("message.label.vacating.form.approval.mail"),
    HOSTEL_CHECK_IN("Hostel Check In"),
    CANCELLED_REJECTED_NOTE("cancelOrRejectedNote"),
    WARDEN("Warden"),
    TO(" to "),
    HM_OFFICE("HM Office"),
    FORMATTED_DONATION_AMOUNT("formattedDonationAmount"),
    STUDENT_WITH_REMARK("studentWithRemark"),
    STUDENT_NAME("studentName"),
    REVOKED("Revoked"),
    ACTIVE("Active"),
    MISSING("MISSING."),
    ROW("Row"),
    STUDENT_ID("Student ID"),
    EXCEL_ERROR_LIST("excelErrorList"),
    RESPONSE("response"),
    STUDENT_ID_NOT_EXIST("studentIDNotExist"),
    HAS_PREV_ID("hasPreviousId"),
    HAS_OVERLAPPING_DATES("hasOverlappingDates"),
    STUDENT_WITH_REMARK_FILE_NAME("StudentWithRemarks"),
    BLACK_LIST_STUDENT("blackListStudent"),
    NORMAL_STUDENT("normalStudent"),
    EXCHANGE_VACATING_REASON("Exchange/Internship prog"),
    MAIL_BODY_OTHERS_HEADER("The following particulars have been submitted for the approval of the accommodation request in one of our campus hostel by"),
    MAIL_BODY_OTHERS_HEADER_CCW_OFFICE("The following particulars have been shortlisted for accommodation request in one of our campus hostel by"),
    FORM_KEY_1("message.label.scholars.stay.extension.dto1"),
    MAX_DATE("message.label.scholars.stay.extension.max.date"),
    IS_GUIDE_NAME_EMAIL_EMPTY("isGuideNameEmailPresent"),
    MAX_MS_PHD_DATE("message.label.scholars.stay.extension.max.ms.phd.date"),
    DATE_FORMAT("date.format"),
    STD_APPOINTMENT_DTO("message.label.student.appointment.dto"),
    FORM_KEY_2("message.label.scholars.stay.extension.dto2"), 
    CATEGORY_CCW("CCW");
    private final String studentConstant;
    StudentConstants(String appointmentConstant) {
        this.studentConstant = appointmentConstant;
    }
}
