package com.iitm.hosteldine.constant.dashboard.student;

import lombok.Getter;
import lombok.ToString;

@Getter
@ToString
public enum WorkflowStatus {
    VALIDATING("Validating"),
    APPROVED("Approved"),
    PENDING("Pending"),
    DEFAULT("Default"),
    CHECKED_IN("CheckedIn"),
    CHECKED_OUT("CheckedOut"),
    CHECK_IN("Check In"),
    CHECK_OUT("Check Out"),
    CHANGE_CHECK_OUT("Change Check Out"),
    VACATE_CHECK_OUT("Vacate Check Out"),
    VACATION_CHECK_OUT("Vacation Check Out"),
    ALLOTTED("Allotted"),
    ALLOCATE("Allocate"),
    REALLOCATE("Reallocate"),
    CANCELLED("Cancelled"),
    VIEW("View"),
    CHANGE("Change"),
    DELETED("Deleted"),
    REJECTED("Rejected"),
    REJECT("Reject"),
    REJECT_REVERSAL("Reject Reversal"),
    APPROVED_WITH_CONDITION("Approved With Condition"),
    APPROVE_WITH_CONDITION("Approve With Condition"),
    CANCELLED_AFTER_APPROVED("CancelledAfterApproval"),
    PAYMENT_CONFIRMED("Payment Confirmed"),
	PAID("Paid"),
	INITIATED("Initiated"),
	COMPLETED("Completed"),
	COMPLETE("Complete"),
	SUCCESS("Success"),
	FAILURE("Failure"),
	ABORTED("Aborted"),
	MS("MS"),
	TRANSFERRED("Transferred"),
    WARDEN_APPROVAL_STATUS_COMPLETE("WardenApproveComplete"),
    OVERRIDE_AND_APPROVED("OverrideAndApproved"),
	RESEND_MAIL("Resend Mail"), 
	RE_SEND_MAIL("Re-send Mail"),
	CHECKBOX("CheckBox"),
	DELETE("Delete"),
	PDF("PDF"),
	REQUIRED("Required"),
	NOT_REQUIRED("Not Required"), 
	OTHERS("Others"),
	APPROVE("Approve"),
    TO_BE_PUSHED("To be Pushed"),
    PUSHED("Pushed"),
    ENABLED("Enabled"),
    PROCESSING("Processing"),
    DUES("Dues"),
    NO_DUES("NoDues"),
    OVERRIDE_APPROVED("OverrideApproved"),
    ALLOTED("Alloted"),
    HOSTEL_CHECKED_ID("Hostel Check In"),
    VACATION_CHECKED_OUT("Vacation CheckedOut"),
    FROM_LOGIN("FROM_LOGIN"),
    FROM_EMAIL("FROM_EMAIL"),
    PAYMENT("Payment"),
    REBATE("Rebate"),
    CLOSED("Closed"),
    TO_BE_REMOVED("To be Removed"),
	REMOVED("Removed"),
	REMOVE("Remove"), 
	VACATE("Vacate"), 
	MESS_CHANGED("Mess Changed"),
	MESS_CHANGE("Mess Change"), 
	SHOW("Show"),
	VACATED("Vacated"), 
	REBATE_TAKEN("Rebate Taken"),
	REQUESTED_FOR_APPROVAL("Requested for Approval"),
	IN_ACTIVE("In-Active"),
	REGULAR("Regular"),
    ACCEPTED("Accepted"),
    ORDER_ACCEPTED("Order Accepted"),
    DELIVERED("Delivered"),
    OUT_FOR_DELIVERY("Out For Delivery"),
    YET_TO_ACCEPT("Yet to Accept"),
    YET_TO_DELIVER("Yet to Deliver"),
    ORDER_PENDING("Order Pending"),
    AUTO_APPROVED("Auto Approved");

    private final String status;
    WorkflowStatus(String status) {
        this.status = status;
    }
}
